### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by samifruit514** [divideandconquer/go-consul-client#6]
When I import values in consul, they are all inside double quotes:

I had to change the client.go code to this:
```
  j := fmt.Sprintf("%v", v)

  result[c.qualify(prefix, k)] = []byte(j)
```

**Comment by divideandconquer** [comment]
This is because everything is run through the json marshaller on import.  If you use the built in helpers like [MustGetString](https://github.com/divideandconquer/go-consul-client/blob/master/src/client/client.go#L141) the quotes will be stripped out by the json unmarshal process.
